#ifndef ROSETTEDATA_H_INCLUDED
#define ROSETTEDATA_H_INCLUDED

enum {
    ROSETTE_MAIN_MENU_TITLE,
    ROSETTE_MAIN_MENU_PLAY_BTN,
    ROSETTE_MAIN_MENU_PLAY_BTN_HOVER,
    ROSETTE_MAIN_MENU_RESUME_BTN,
    ROSETTE_MAIN_MENU_RESUME_BTN_HOVER,
    ROSETTE_MAIN_MENU_HELP_BTN,
    ROSETTE_MAIN_MENU_HELP_BTN_HOVER,
    ROSETTE_MAIN_MENU_QUIT_BTN,
    ROSETTE_MAIN_MENU_QUIT_BTN_HOVER,
    ROSETTE_GAME_EXIT_BTN,
    ROSETTE_GAME_EXIT_BTN_HOVER,
    ROSETTE_GAME_RESUME_BTN,
    ROSETTE_GAME_RESUME_BTN_HOVER,
    ROSETTE_GAME_NEW_BTN,
    ROSETTE_GAME_NEW_BTN_HOVER,
    ROSETTE_GAME_PASS_BTN,
    ROSETTE_GAME_PASS_BTN_HOVER,
    ROSETTE_GAME_QUIT_BTN,
    ROSETTE_GAME_QUIT_BTN_HOVER,
    ROSETTE_INTRO_BG,
    ROSETTE_MAIN_BG,
    ROSETTE_HUD_TITLE_FONT,
    ROSETTE_HUD_SCORE_FONT,
    ROSETTE_HUD_LEFT_PAWN_FONT,
    ROSETTE_DATA_COUNT
};

#endif // ROSETTEDATA_H_INCLUDED
